Repository BinaryStudioAcademy/bsa-2018-polyglot, pull requests merged in 2018-09, with the labels that each got.

#393 Feature/Сhat
  backend/Polyglot.BusinessLogic/Hubs/BaseHub.cs
  backend/Polyglot.BusinessLogic/Hubs/ChatHub.cs
  backend/Polyglot.BusinessLogic/Hubs/WorkspaceHub.cs
  backend/Polyglot.BusinessLogic/Infrastructure.cs
  backend/Polyglot.BusinessLogic/Interfaces/IChatService.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISiganlRWorkspaceService.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/ChatService.cs
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRWorkspaceService.cs
  backend/Polyglot.Common/DTOs/Chat/ChatContactsDTO.cs
  backend/Polyglot.Common/DTOs/Chat/ChatMessageDTO.cs
  backend/Polyglot.Common/DTOs/Chat/ChatUserDTO.cs
  backend/Polyglot.Common/DTOs/Chat/ChatUserState.cs
  backend/Polyglot.Common/DTOs/TeamPrevDTO.cs
  backend/Polyglot.Common/Helpers/ChatGroup.cs
  backend/Polyglot.Common/Helpers/SignalR/ChatAction.cs
  backend/Polyglot.Common/Helpers/SignalR/Group.cs
  backend/Polyglot.DataAccess/Entities/Chat/ChatMessage.cs
  backend/Polyglot.DataAccess/Entities/Chat/Message.cs
  backend/Polyglot/Controllers/ChatController.cs
  backend/Polyglot/Startup.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/app.module.ts
  frontend/src/app/common/app-routing-module/app-routing.module.ts
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.html
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.sass
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.spec.ts
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.html
  frontend/src/app/components/chat/chat-window/chat-window.component.sass
  frontend/src/app/components/chat/chat-window/chat-window.component.spec.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/chat/chat.component.html
  frontend/src/app/components/chat/chat.component.sass
  frontend/src/app/components/chat/chat.component.spec.ts
  frontend/src/app/components/chat/chat.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/chat/chatContacts.ts
  frontend/src/app/models/chat/chatMessage.ts
  frontend/src/app/models/chat/chatUser.ts
  frontend/src/app/models/chat/groupType.ts
  frontend/src/app/models/chat/userState.ts
  frontend/src/app/models/index.ts
  frontend/src/app/models/signalrModels/chat-actions.ts
  frontend/src/app/models/signalrModels/hub.ts
  frontend/src/app/models/signalrModels/signalr-groups.ts
  frontend/src/app/services/chat.service.spec.ts
  frontend/src/app/services/chat.service.ts
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#408 Fix/high
  backend/Polyglot.BusinessLogic/Interfaces/IComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot/Controllers/ComplexStringsController.cs
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/services/complex-string.service.ts
Labels: enhancement

#409 Feature/comments improvement
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/project-details/project-team/project-team.component.ts
  frontend/src/app/dialogs/team-assign/team-assign.component.sass
Labels: bug fix, enhancement

#407 Feature/Сhat
  backend/Polyglot.BusinessLogic/Hubs/BaseHub.cs
  backend/Polyglot.BusinessLogic/Hubs/ChatHub.cs
  backend/Polyglot.BusinessLogic/Interfaces/IChatService.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/ChatService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRChatService.cs
  backend/Polyglot.Common/DTOs/Chat/ChatContactsDTO.cs
  backend/Polyglot.Common/DTOs/Chat/ChatUserDTO.cs
  backend/Polyglot.Common/Helpers/ChatGroup.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot/Authentication/ApplicationBuilderExtensions.cs
  backend/Polyglot/Controllers/ChatController.cs
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.html
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.sass
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.html
  frontend/src/app/components/chat/chat-window/chat-window.component.sass
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/chat/chat.component.html
  frontend/src/app/components/chat/chat.component.sass
  frontend/src/app/components/chat/chat.component.ts
  frontend/src/app/models/chat/chatUser.ts
  frontend/src/app/services/chat.service.ts
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#428 Fix/stat
  frontend/src/app/components/about-us/about-us.component.html
  frontend/src/app/components/contact/contact.component.html
  frontend/src/app/components/manager-profile/manager-profile.component.html
  frontend/src/app/components/new-project/new-project.component.html
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/user-settings/user-settings.component.html
Labels: bug

#437 add overlay for profile photos + fix teams Add
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.DataAccess/SqlRepository/Repository.cs
  frontend/src/app/components/manager-profile/manager-profile.component.html
  frontend/src/app/components/manager-profile/manager-profile.component.sass
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.html
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.sass
  frontend/src/app/components/user-settings/user-settings.component.html
  frontend/src/app/components/user-settings/user-settings.component.sass
Labels: bug fix, enhancement

#445 Fix/custom input bugs
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/environments/environment.ts
Labels: bug, enhancement

#446 Notifications
  backend/Polyglot.BusinessLogic/Hubs/NavigationHub.cs
  backend/Polyglot.BusinessLogic/Infrastructure.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISignaRNavigationService.cs
  backend/Polyglot.BusinessLogic/Services/NotificationService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRNavigationService.cs
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.Common/Helpers/SignalR/Action.cs
  backend/Polyglot.Common/Helpers/SignalR/Group.cs
  backend/Polyglot/Controllers/TeamsController.cs
  backend/Polyglot/Startup.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/navigation/navigation.component.ts
  frontend/src/app/components/notifications/notifications.component.ts
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/signalrModels/hub.ts
  frontend/src/app/models/signalrModels/signalr-groups.ts
  frontend/src/app/models/signalrModels/signalr-subscribe-actions.ts
  frontend/src/app/services/signalr.service.ts
  frontend/src/app/services/user.service.ts
Labels: bug, enhancement

#453 implemented ability to add member to team
  backend/Polyglot.BusinessLogic/Interfaces/ICRUDService.cs
  backend/Polyglot.BusinessLogic/Interfaces/ITeamService.cs
  backend/Polyglot.BusinessLogic/Services/CRUDService.cs
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.Common/DTOs/TeamTranslatorsDTO.cs
  backend/Polyglot.DataAccess/Interfaces/IRepository.cs
  backend/Polyglot.DataAccess/MongoRepository/MongoRepository.cs
  backend/Polyglot.DataAccess/SqlRepository/Repository.cs
  backend/Polyglot/Controllers/TeamsController.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/chat/chat.component.ts
  frontend/src/app/components/manager-profile/manager-profile.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/team-details/team-members/team-members.component.html
  frontend/src/app/components/team-details/team-members/team-members.component.sass
  frontend/src/app/components/team-details/team-members/team-members.component.ts
  frontend/src/app/components/teams/new-team/new-team.component.html
  frontend/src/app/components/teams/new-team/new-team.component.sass
  frontend/src/app/components/teams/new-team/new-team.component.ts
  frontend/src/app/components/translatorProfile/star-rating/star-rating.component.html
  frontend/src/app/components/upload-image/upload-image.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/dialogs/choose-proficiency-dialog/choose-proficiency-dialog.component.html
  frontend/src/app/dialogs/choose-proficiency-dialog/choose-proficiency-dialog.component.sass
  frontend/src/app/dialogs/team-add-member/team-add-member.component.html
  frontend/src/app/dialogs/team-add-member/team-add-member.component.sass
  frontend/src/app/dialogs/team-add-member/team-add-member.component.spec.ts
  frontend/src/app/dialogs/team-add-member/team-add-member.component.ts
  frontend/src/app/directives/noWhiteSpace.directive.ts
  frontend/src/app/services/teams.service.ts
Labels: bug, enhancement

#457 Fixed some bugs
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: bug

#458 Fixed bugs
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: bug, bug fix

#460 hotfixes
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: bug, bug fix

#461 Feature/signal r improvement
  backend/Polyglot.BusinessLogic/Hubs/ChatHub.cs
  backend/Polyglot.BusinessLogic/Hubs/NavigationHub.cs
  backend/Polyglot/Authentication/ApplicationBuilderExtensions.cs
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#462 Fixed scroll on dashboard
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/workspace.component.html
Labels: bug, bug fix

#464 Added placeholder and spinner
  frontend/src/app/components/manager-profile/manager-profile.component.html
  frontend/src/app/components/manager-profile/manager-profile.component.sass
  frontend/src/app/components/manager-profile/manager-profile.component.ts
Labels: enhancement

#465 Feature/assign languages
  backend/Polyglot.BusinessLogic/Interfaces/ILanguageService.cs
  backend/Polyglot.BusinessLogic/Services/LanguageService.cs
  backend/Polyglot/Controllers/LanguagesController.cs
  frontend/src/app/app.module.ts
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.html
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.ts
  frontend/src/app/dialogs/add-remove-languages-dialog/add-remove-languages-dialog.component.html
  frontend/src/app/dialogs/add-remove-languages-dialog/add-remove-languages-dialog.component.sass
  frontend/src/app/dialogs/add-remove-languages-dialog/add-remove-languages-dialog.component.spec.ts
  frontend/src/app/dialogs/add-remove-languages-dialog/add-remove-languages-dialog.component.ts
  frontend/src/app/dialogs/choose-proficiency-dialog/choose-proficiency-dialog.component.html
  frontend/src/app/dialogs/choose-proficiency-dialog/choose-proficiency-dialog.component.sass
  frontend/src/app/dialogs/choose-proficiency-dialog/choose-proficiency-dialog.component.ts
  frontend/src/app/services/language.service.ts
Labels: enhancement

#470 Fixed active string translation highlighting logic
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
Labels: bug, bug fix

#472 fixed problem
  frontend/src/app/common/pipes/comments.pipe.ts
Labels: bug, bug fix

#471 Feature/remove team translator
  backend/Polyglot.BusinessLogic/Interfaces/ITeamService.cs
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.Common/DTOs/TeamTranslatorsDTO.cs
  backend/Polyglot/Controllers/TeamsController.cs
  frontend/src/app/components/notifications/notifications.component.ts
  frontend/src/app/components/team-details/team-members/team-members.component.html
  frontend/src/app/components/team-details/team-members/team-members.component.ts
  frontend/src/app/dialogs/confirm-dialog/confirm-dialog.component.sass
  frontend/src/app/services/teams.service.ts
Labels: bug, enhancement

#475 Feature/guideline
  frontend/src/app/app.module.ts
  frontend/src/app/common/app-routing-module/app-routing.module.ts
  frontend/src/app/components/guideline/guideline.component.html
  frontend/src/app/components/guideline/guideline.component.sass
  frontend/src/app/components/guideline/guideline.component.spec.ts
  frontend/src/app/components/guideline/guideline.component.ts
  frontend/src/app/components/guideline/manager-guide/manager-guide.component.html
  frontend/src/app/components/guideline/manager-guide/manager-guide.component.sass
  frontend/src/app/components/guideline/manager-guide/manager-guide.component.spec.ts
  frontend/src/app/components/guideline/manager-guide/manager-guide.component.ts
  frontend/src/app/components/guideline/translator-guide/translator-guide.component.html
  frontend/src/app/components/guideline/translator-guide/translator-guide.component.sass
  frontend/src/app/components/guideline/translator-guide/translator-guide.component.spec.ts
  frontend/src/app/components/guideline/translator-guide/translator-guide.component.ts
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/assets/images/guideline/Comments.PNG
  frontend/src/assets/images/guideline/CreateProject.PNG
  frontend/src/assets/images/guideline/CreateString.PNG
  frontend/src/assets/images/guideline/CreateTeam.PNG
  frontend/src/assets/images/guideline/Glossary.PNG
  frontend/src/assets/images/guideline/GlossaryUsage.PNG
  frontend/src/assets/images/guideline/History.PNG
  frontend/src/assets/images/guideline/Invitation.PNG
  frontend/src/assets/images/guideline/MachineTranslation.PNG
  frontend/src/assets/images/guideline/Optional.PNG
  frontend/src/assets/images/guideline/Progress.PNG
  frontend/src/assets/images/guideline/Report.PNG
  frontend/src/assets/images/guideline/Translate.PNG
Labels: enhancement

#480 Feature/chat impovement
  backend/Polyglot.BusinessLogic/Hubs/ChatHub.cs
  backend/Polyglot.BusinessLogic/Infrastructure.cs
  backend/Polyglot.BusinessLogic/Interfaces/IChatService.cs
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/ChatService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRCommonService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/UserIdProvider.cs
  backend/Polyglot.Common/DTOs/Chat/ChatMessageDTO.cs
  backend/Polyglot.Common/DTOs/Chat/ChatUserDTO.cs
  backend/Polyglot.Common/DTOs/ProjectDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot.DataAccess/MongoModels/Priority.cs
  backend/Polyglot.DataAccess/MongoModels/ProjectPriority.cs
  backend/Polyglot/Controllers/OptionsController.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.html
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.sass
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.html
  frontend/src/app/components/chat/chat-window/chat-window.component.sass
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/projects/projects.component.html
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/chat/chatMessage.ts
  frontend/src/app/models/chat/chatUser.ts
  frontend/src/app/models/chat/groupType.ts
  frontend/src/app/models/project.ts
  frontend/src/app/services/project.service.ts
  frontend/src/app/services/signalr.service.ts
Labels: bug fix, enhancement

#481 Fixed input width
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: bug, bug fix

#482 Fixed input editing
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: bug, bug fix

#485 Fix/teams fixes
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.DataAccess/Helpers/Proficiency.cs
  backend/Polyglot.DataAccess/Seeds/ModelBuilderExtensions.cs
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/teams/new-team/new-team.component.html
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/services/http.service.ts
Labels: bug fix

#486 Fixed bug with email login
  frontend/src/app/dialogs/login-dialog/login-dialog.component.ts
Labels: bug, bug fix

#489 Added some project and string description markup
  frontend/src/app/components/project-details/project-details.component.html
  frontend/src/app/components/workspace/key-details/tab-detail/tab-detail.component.html
Labels: enhancement

#493 Fixed some logic
  frontend/src/app/components/workspace/workspace.component.ts
Labels: bug, bug fix

#494 Fix/project priority fix
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.DataAccess/MongoModels/ProjectPriority.cs
Labels: bug fix

#495 Fix/project priority fix
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
Labels: bug fix

#498 Fix/translation assign
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
Labels: bug, bug fix

#501 Fixed some markup bugs
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/key-details/tab-optional/tab-optional.component.html
  frontend/src/app/components/workspace/key-details/tab-optional/tab-optional.component.ts
  frontend/src/app/dialogs/string-dialog/string-dialog.component.html
Labels: bug, bug fix

#503 Fixed some markup bugs
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.html
Labels: bug, bug fix

#508 Fixed sign up notifications, fixed input bug
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.ts
  frontend/src/app/services/auth.service.ts
Labels: bug, bug fix

#513 Feature/chat impovement
  backend/Polyglot.BusinessLogic/Hubs/ChatHub.cs
  backend/Polyglot.BusinessLogic/Interfaces/IChatService.cs
  backend/Polyglot.BusinessLogic/Interfaces/SignalR/ISignalRChatService.cs
  backend/Polyglot.BusinessLogic/Services/ChatService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRChatService.cs
  backend/Polyglot.Common/Helpers/SignalR/ChatAction.cs
  backend/Polyglot.DataAccess/MongoModels/Priority.cs
  backend/Polyglot.DataAccess/MongoModels/ProjectPriority.cs
  backend/Polyglot/Controllers/ChatController.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.html
  frontend/src/app/components/chat/chat-window/chat-window.component.sass
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/models/chat/userState.ts
  frontend/src/app/models/signalrModels/chat-actions.ts
  frontend/src/app/services/chat.service.ts
Labels: enhancement

#515 Fix/mentions markup + registration date
  backend/Polyglot/Controllers/UserProfilesController.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/project-details/project-activities/project-activities.component.ts
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/teams/new-team/new-team.component.html
  frontend/src/app/components/teams/new-team/new-team.component.ts
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.html
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.sass
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.ts
  frontend/src/app/components/workspace/key-details/tab-history/tab-history.component.html
  frontend/src/app/dialogs/team-add-member/team-add-member.component.html
  frontend/src/app/dialogs/team-add-member/team-add-member.component.sass
  frontend/src/app/dialogs/team-add-member/team-add-member.component.ts
  frontend/src/app/models/proficiency.ts
  frontend/src/index.html
Labels: enhancement

#517 Fix/chat dialog hash
  backend/Polyglot.BusinessLogic/Services/ChatService.cs
  backend/Polyglot.Common/DTOs/Chat/ChatUserDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot.DataAccess/Entities/UserProfile.cs
  frontend/src/app/components/chat/chat-contacts/chat-contacts.component.ts
  frontend/src/app/components/chat/chat-window/chat-window.component.ts
  frontend/src/app/models/chat/chatUser.ts
Labels: bug fix

#520 Fixed user settings save
  backend/Polyglot/Controllers/UserProfilesController.cs
  frontend/src/app/components/team-details/team-members/team-members.component.html
  frontend/src/app/components/teams/new-team/new-team.component.html
  frontend/src/app/components/teams/new-team/new-team.component.sass
  frontend/src/app/components/teams/new-team/new-team.component.ts
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.html
  frontend/src/app/components/user-settings/user-settings.component.ts
Labels: bug fix
