Repository BinaryStudioAcademy/bsa-2018-polyglot, pull requests merged in 2018-08, with the labels that each got.

#2 Feature/http client wrapper
  backend/Polyglot.BusinessLogic/Implementations/HttpServices/HttpService.cs
  backend/Polyglot.BusinessLogic/Interfaces/IHttpService.cs
  backend/Polyglot.BusinessLogic/Polyglot.BusinessLogic.csproj
  backend/Polyglot.sln
Labels: enhancement

#3 Feature/data service
  backend/Polyglot.BusinessLogic/Implementations/HttpServices/HttpService.cs
  frontend/src/app/app.module.ts
  frontend/src/app/landing.component.ts
  frontend/src/app/services/data.service.ts
Labels: enhancement

#5 parametr fix
  frontend/src/app/services/data.service.ts
Labels: bug

#7 fix bug
  frontend/src/app/app.module.ts
Labels: bug

#8 fix parametres problem + correct polyglot
  backend/Polyglot.BusinessLogic/Implementations/HttpServices/HttpService.cs
  frontend/src/app/services/data.service.ts
Labels: bug

#10 fix
  frontend/src/app/services/data.service.spec.ts
Labels: bug

#13 implement hamburger menu
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/navigation/navigation.component.sass
  frontend/src/app/components/navigation/navigation.component.ts
Labels: enhancement

#17 Feature/sql models
  backend/Polyglot.DataAccess/Entities/File.cs
  backend/Polyglot.DataAccess/Entities/Glossary.cs
  backend/Polyglot.DataAccess/Entities/Language.cs
  backend/Polyglot.DataAccess/Entities/Manager.cs
  backend/Polyglot.DataAccess/Entities/Project.cs
  backend/Polyglot.DataAccess/Entities/ProjectGlossary.cs
  backend/Polyglot.DataAccess/Entities/ProjectHistory.cs
  backend/Polyglot.DataAccess/Entities/ProjectLanguage.cs
  backend/Polyglot.DataAccess/Entities/ProjectTag.cs
  backend/Polyglot.DataAccess/Entities/Rating.cs
  backend/Polyglot.DataAccess/Entities/Right.cs
  backend/Polyglot.DataAccess/Entities/Tag.cs
  backend/Polyglot.DataAccess/Entities/Team.cs
  backend/Polyglot.DataAccess/Entities/TeamTranslator.cs
  backend/Polyglot.DataAccess/Entities/Translation.cs
  backend/Polyglot.DataAccess/Entities/Translator.cs
  backend/Polyglot.DataAccess/Entities/TranslatorLanguage.cs
  backend/Polyglot.DataAccess/Entities/TranslatorRight.cs
  backend/Polyglot.DataAccess/Entities/User.cs
  backend/Polyglot.DataAccess/Entities/UserProfile.cs
Labels: enhancement

#28 dto-s added
  backend/Polyglot.Common/DTOs/FileDTO.cs
  backend/Polyglot.Common/DTOs/GlossaryDTO.cs
  backend/Polyglot.Common/DTOs/LanguageDTO.cs
  backend/Polyglot.Common/DTOs/ManagerDTO.cs
  backend/Polyglot.Common/DTOs/ProjectDTO.cs
  backend/Polyglot.Common/DTOs/ProjectGlossaryDTO.cs
  backend/Polyglot.Common/DTOs/ProjectHistoryDTO.cs
  backend/Polyglot.Common/DTOs/ProjectLanguageDTO.cs
  backend/Polyglot.Common/DTOs/ProjectTagDTO.cs
  backend/Polyglot.Common/DTOs/RatingDTO.cs
  backend/Polyglot.Common/DTOs/RightDTO.cs
  backend/Polyglot.Common/DTOs/TagDTO.cs
  backend/Polyglot.Common/DTOs/TeamDTO.cs
  backend/Polyglot.Common/DTOs/TeamTranslatorDTO.cs
  backend/Polyglot.Common/DTOs/TranslationDTO.cs
  backend/Polyglot.Common/DTOs/TranslatorDTO.cs
  backend/Polyglot.Common/DTOs/TranslatorLanguageDTO.cs
  backend/Polyglot.Common/DTOs/TranslatorRightDTO.cs
  backend/Polyglot.Common/DTOs/UserDTO.cs
  backend/Polyglot.Common/DTOs/UserProfileDTO.cs
  backend/Polyglot.Common/Polyglot.Common.csproj.user
Labels: enhancement

#30 Feature/dto mapping
  backend/Polyglot.Common/DTOs/NoSQL/AdditionalTranslationDTO.cs
  backend/Polyglot.Common/DTOs/NoSQL/CommentDTO.cs
  backend/Polyglot.Common/DTOs/NoSQL/ComplexStringDTO.cs
  backend/Polyglot.Common/DTOs/NoSQL/TranslationDTO.cs
  backend/Polyglot.Common/DTOs/TranslationDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot.DataAccess/Entities/Translation.cs
Labels: enhancement

#33 Feature/login singin dialogs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/landing/home/home.component.html
  frontend/src/app/components/landing/home/home.component.ts
  frontend/src/app/components/landing/landing.component.ts
  frontend/src/app/components/landing/navigation/navigation.component.html
  frontend/src/app/components/landing/navigation/navigation.component.ts
  frontend/src/app/dialogs/login-dialog/login-dialog.component.html
  frontend/src/app/dialogs/login-dialog/login-dialog.component.sass
  frontend/src/app/dialogs/login-dialog/login-dialog.component.spec.ts
  frontend/src/app/dialogs/login-dialog/login-dialog.component.ts
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.html
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.sass
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.spec.ts
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.ts
  frontend/src/app/models/index.ts
  frontend/src/app/models/user-login.d.ts
  frontend/src/app/models/user-signup.d.ts
  frontend/src/app/models/user.d.ts
  frontend/src/common-styles/_flex-utils.sass
  frontend/src/common-styles/_spacers-utils.sass
  frontend/src/common-styles/all.sass
  frontend/src/styles.sass
Labels: enhancement

#39 Feature/crud
  backend/Polyglot.BusinessLogic/Interfaces/ICRUDService.cs
  backend/Polyglot.BusinessLogic/Interfaces/IHttpService.cs
  backend/Polyglot.BusinessLogic/Interfaces/IUserService.cs
  backend/Polyglot.BusinessLogic/Polyglot.BusinessLogic.csproj
  backend/Polyglot.Common/DTOs/ProjectGlossaryDTO.cs
  backend/Polyglot.Common/DTOs/ProjectLanguageDTO.cs
  backend/Polyglot.Common/DTOs/ProjectTagDTO.cs
  backend/Polyglot.Common/DTOs/TranslatorLanguageDTO.cs
  backend/Polyglot.Common/DTOs/TranslatorRightDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot.DataAccess/Entities/Entity.cs
  backend/Polyglot.DataAccess/Entities/File.cs
  backend/Polyglot.DataAccess/Entities/Glossary.cs
  backend/Polyglot.DataAccess/Entities/Language.cs
  backend/Polyglot.DataAccess/Entities/Manager.cs
  backend/Polyglot.DataAccess/Entities/Project.cs
  backend/Polyglot.DataAccess/Entities/ProjectGlossary.cs
  backend/Polyglot.DataAccess/Entities/ProjectHistory.cs
  backend/Polyglot.DataAccess/Entities/ProjectLanguage.cs
  backend/Polyglot.DataAccess/Entities/ProjectTag.cs
  backend/Polyglot.DataAccess/Entities/Rating.cs
  backend/Polyglot.DataAccess/Entities/Right.cs
  backend/Polyglot.DataAccess/Entities/Tag.cs
  backend/Polyglot.DataAccess/Entities/Team.cs
  backend/Polyglot.DataAccess/Entities/TeamTranslator.cs
  backend/Polyglot.DataAccess/Entities/Translation.cs
  backend/Polyglot.DataAccess/Entities/Translator.cs
  backend/Polyglot.DataAccess/Entities/TranslatorLanguage.cs
  backend/Polyglot.DataAccess/Entities/TranslatorRight.cs
  backend/Polyglot.DataAccess/Entities/UserProfile.cs
  backend/Polyglot/Controllers/FilesController.cs
  backend/Polyglot/Controllers/GlossariesController.cs
  backend/Polyglot/Controllers/LanguagesController.cs
  backend/Polyglot/Controllers/MangersController.cs
  backend/Polyglot/Controllers/ProjectGlossariesController.cs
  backend/Polyglot/Controllers/ProjectHistoriesController.cs
  backend/Polyglot/Controllers/ProjectLanguagesController.cs
  backend/Polyglot/Controllers/ProjectTagsController.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/Controllers/RatingsController.cs
  backend/Polyglot/Controllers/RightsController.cs
  backend/Polyglot/Controllers/TagsController.cs
  backend/Polyglot/Controllers/TeamsController.cs
  backend/Polyglot/Controllers/TranslatorLanguagesController.cs
  backend/Polyglot/Controllers/TranslatorRightsController.cs
  backend/Polyglot/Controllers/TranslatorsController.cs
  backend/Polyglot/Polyglot.csproj
Labels: enhancement

#63 fix dashdoard margins
  frontend/src/app/components/projects/projects.component.sass
  frontend/src/app/components/teams/teams.component.sass
Labels: bug

#78 Fix/navigation
  frontend/src/app/app.module.ts
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/navigation/navigation.component.sass
  frontend/src/app/components/navigation/navigation.component.ts
  frontend/src/app/dialogs/signup-dialog/signup-dialog.component.html
Labels: bug, enhancement

#93 Fix/navigation
  .vscode/launch.json
  .vscode/tasks.json
  backend/Polyglot/appsettings.json
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/projects/projects.component.html
  frontend/src/assets/images/project.jpg
Labels: bug

#97 Feature/projects inclusion
  backend/Polyglot.BusinessLogic/Implementations/CRUDService.cs
  backend/Polyglot.BusinessLogic/Interfaces/ICRUDService.cs
  backend/Polyglot.DataAccess/Interfaces/IRepository.cs
  backend/Polyglot.DataAccess/NoSQL_Repository/Repository.cs
  backend/Polyglot.DataAccess/Repositories/Repository.cs
  backend/Polyglot/Controllers/ProjectsController.cs
Labels: enhancement

#109 fix select image hovering
  frontend/src/app/components/upload-image/upload-image.component.sass
Labels: enhancement

#197 Feature/adding language to project
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.Common/DTOs/LanguageDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/appsettings.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/new-project/new-project.component.ts
  frontend/src/app/components/project-details/languages/languages.component.html
  frontend/src/app/components/project-details/languages/languages.component.sass
  frontend/src/app/components/project-details/languages/languages.component.spec.ts
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/project-details/project-details.component.html
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.html
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.sass
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.spec.ts
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.ts
  frontend/src/app/dialogs/select-project-language/select-project-language.component.html
  frontend/src/app/dialogs/select-project-language/select-project-language.component.sass
  frontend/src/app/dialogs/select-project-language/select-project-language.component.spec.ts
  frontend/src/app/dialogs/select-project-language/select-project-language.component.ts
  frontend/src/app/services/project.service.ts
Labels: enhancement

#228 Feature/assignig_team_to_project
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.DataAccess/Entities/Entity.cs
  backend/Polyglot.DataAccess/Seeds/ModelBuilderExtensions.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/project-details/project-details.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/project-details/project-team/project-team.component.spec.ts
  frontend/src/app/components/project-details/project-team/project-team.component.ts
  frontend/src/app/components/project-details/project-team/utils.ts
  frontend/src/app/components/project-edit/project-edit.component.ts
  frontend/src/app/components/teams/teams.component.sass
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.html
  frontend/src/app/dialogs/delete-project-language/delete-project-language.component.ts
  frontend/src/app/dialogs/select-project-language/select-project-language.component.html
  frontend/src/app/dialogs/select-project-language/select-project-language.component.ts
  frontend/src/app/dialogs/team-assign/team-assign.component.html
  frontend/src/app/dialogs/team-assign/team-assign.component.sass
  frontend/src/app/dialogs/team-assign/team-assign.component.spec.ts
  frontend/src/app/dialogs/team-assign/team-assign.component.ts
  frontend/src/app/services/project.service.ts
Labels: enhancement

#233 fix button disabled
  frontend/src/app/dialogs/team-assign/team-assign.component.html
  frontend/src/app/dialogs/team-assign/team-assign.component.ts
Labels: bug

#246 Feature/ui improvement
  frontend/src/app/components/project-details/languages/languages.component.html
  frontend/src/app/components/project-details/languages/languages.component.sass
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/project-details/project-team/project-team.component.ts
  frontend/src/app/components/teams/team/team.component.html
  frontend/src/app/components/teams/team/team.component.ts
  frontend/src/app/dialogs/team-assign/team-assign.component.ts
Labels: enhancement

#247 show photo in project settings
  frontend/src/app/components/project-edit/project-edit.component.html
  frontend/src/app/components/upload-image/upload-image.component.html
  frontend/src/app/components/upload-image/upload-image.component.sass
  frontend/src/app/components/upload-image/upload-image.component.ts
Labels: enhancement

#251 Feature/ui improvement
  frontend/src/app/components/project-details/languages/languages.component.html
  frontend/src/app/components/project-details/languages/languages.component.sass
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/project-details/project-team/project-team.component.sass
  frontend/src/app/components/project-details/project-team/project-team.component.ts
Labels: enhancement

#284 Fix/data adapter
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot/appsettings.json
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/common/app-material/app-material.module.ts
  frontend/src/app/common/dateAdapter/date-format.ts
  frontend/src/app/components/manager-profile/manager-profile.component.ts
  frontend/src/app/components/navigation/navigation.component.ts
  frontend/src/app/components/project-details/project-activities/project-activities.component.html
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/translatorProfile/tab-review/tab-review.component.html
  frontend/src/app/components/translatorProfile/tab-review/tab-review.component.ts
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.ts
  frontend/src/app/components/user-profile/user-profile.component.ts
  frontend/src/app/components/user-settings/user-settings.component.ts
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.html
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.ts
  frontend/src/app/components/workspace/key-details/tab-history/tab-history.component.html
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/services/guards/auth-guard.service.ts
  frontend/src/app/services/user.service.ts
Labels: enhancement

#286 fixes
  frontend/src/app/components/teams/new-team/new-team.component.ts
  frontend/src/app/components/teams/teams.component.sass
Labels: bug

#302 Fix/complex string removing
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.Common/DTOs/LanguageDTO.cs
  backend/Polyglot.Common/Mapping/AutoMapper.cs
  backend/Polyglot.Core/Authentication/CurrentUser.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/Hubs/Interfaces/ISignalrWorkspaceService.cs
  backend/Polyglot/Polyglot.csproj.user
  backend/Polyglot/Startup.cs
  frontend/package-lock.json
  frontend/src/app/components/project-details/project-activities/project-activities.component.ts
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/key-details/tab-glossary/tab-glossary.component.ts
  frontend/src/app/components/workspace/workspace.component.html
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/dialogs/string-dialog/string-dialog.component.html
  frontend/src/app/services/project.service.ts
  frontend/src/app/services/signalr.service.ts
Labels: bug, enhancement

#308 Fix/complex string removing
  backend/Polyglot.BusinessLogic/Interfaces/IProjectService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot/appsettings.json
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/services/project.service.ts
Labels: enhancement

#309 simplest lifecycle managment implemented
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#314 Feature/complex string reloading background
  backend/Polyglot/Controllers/ComplexStringsController.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/Hubs/Helpers/Actions.cs
  backend/Polyglot/Hubs/Helpers/Groups.cs
  backend/Polyglot/Hubs/Interfaces/ISignalrWorkspaceService.cs
  backend/Polyglot/Hubs/Services/SignalrWorkspaceService.cs
  backend/Polyglot/Hubs/SignalrSubscribeActions.cs
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/signalrModels/signalr-groups.ts
  frontend/src/app/models/signalrModels/signalr-subscribe-actions.ts
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#323 Feature/languages background reloading
  backend/Polyglot/Controllers/ComplexStringsController.cs
  backend/Polyglot/Hubs/Helpers/Actions.cs
  backend/Polyglot/Hubs/Interfaces/ISignalrWorkspaceService.cs
  backend/Polyglot/Hubs/Services/SignalrWorkspaceService.cs
  backend/Polyglot/Hubs/WorkspaceHub.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/signalrModels/signalr-subscribe-actions.ts
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#336 Feature/language translations reloading background
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/services/signalr.service.ts
Labels: enhancement

#339 Fix/ui
  frontend/src/app/app.component.html
  frontend/src/app/components/glossaries/glossaries.component.sass
  frontend/src/app/components/glossaries/glossary/glossary.component.sass
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/navigation/navigation.component.sass
  frontend/src/app/components/project-details/project-details.component.sass
  frontend/src/app/components/projects/projects.component.sass
  frontend/src/app/components/teams/teams.component.sass
  frontend/src/app/components/workspace/key-details/key-details.component.sass
Labels: bug, enhancement

#369 Fixed bug with scroll after deleting string
  frontend/src/app/components/workspace/workspace.component.ts
Labels: bug

#372 Fixed bug with creating new project
  frontend/src/app/dialogs/project-message/project-message.component.html
Labels: bug

#371 Fixed bug with default avatar
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/projects/projects.component.html
Labels: bug

#370 Resolve issue with tags duplicate in filter
  frontend/src/app/components/workspace/workspace.component.ts
Labels: bug

#374 Feature edit/delete comment
  backend/Polyglot.BusinessLogic/Interfaces/IComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot.Common/DTOs/NoSQL/CommentDTO.cs
  backend/Polyglot.DataAccess/MongoModels/Comment.cs
  backend/Polyglot/Controllers/ComplexStringsController.cs
  backend/Polyglot/Hubs/Helpers/Actions.cs
  backend/Polyglot/Hubs/Interfaces/ISignalrWorkspaceService.cs
  backend/Polyglot/Hubs/Services/SignalrWorkspaceService.cs
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.sass
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.html
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.sass
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.ts
  frontend/src/app/components/workspace/key/key.component.ts
  frontend/src/app/components/workspace/workspace.component.html
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/models/comment.ts
  frontend/src/app/services/comments.service.spec.ts
  frontend/src/app/services/comments.service.ts
  frontend/src/app/services/complex-string.service.ts
Labels: enhancement

#376 Added some styles to bell icon
  frontend/src/app/components/navigation/navigation.component.html
  frontend/src/app/components/navigation/navigation.component.sass
  frontend/src/styles.sass
Labels: enhancement

#375 Added 'Save' button disabling when nothing changed or input is empty
  frontend/src/app/components/workspace/key-details/key-details.component.html
  frontend/src/app/components/workspace/key-details/key-details.component.ts
Labels: enhancement

#368 Feature/signal r refactoring
  backend/Polyglot.BusinessLogic/Hubs/WorkspaceHub.cs
  backend/Polyglot.BusinessLogic/Infrastructure.cs
  backend/Polyglot.BusinessLogic/Interfaces/ISiganlRWorkspaceService.cs
  backend/Polyglot.BusinessLogic/Polyglot.BusinessLogic.csproj
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ProjectService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRCommonService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRWorkspaceService.cs
  backend/Polyglot.Common/Helpers/SignalR/Action.cs
  backend/Polyglot.Common/Helpers/SignalR/Group.cs
  backend/Polyglot.Core/SignalR/Responses/EntitiesIdsResponse.cs
  backend/Polyglot.Core/SignalR/Responses/IResponse.cs
  backend/Polyglot/Controllers/ComplexStringsController.cs
  backend/Polyglot/Controllers/ProjectTranslatorsController.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/Hubs/Interfaces/ISignalrWorkspaceService.cs
  backend/Polyglot/Hubs/Services/SignalrCommonService.cs
  backend/Polyglot/Hubs/Services/SignalrWorkspaceService.cs
  backend/Polyglot/Hubs/WorkspaceHub.cs
  backend/Polyglot/Startup.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/project-details/languages/languages.component.ts
  frontend/src/app/components/projects/projects.component.ts
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/key/key.component.ts
  frontend/src/app/components/workspace/workspace.component.html
  frontend/src/app/components/workspace/workspace.component.ts
  frontend/src/app/services/complex-string.service.ts
  frontend/src/app/services/project.service.ts
  frontend/src/app/services/signalr.service.ts
  frontend/src/app/services/translation.service.ts
Labels: enhancement

#377 Default user avatar url now sets on backend
  backend/Polyglot/Controllers/UserProfilesController.cs
  frontend/src/app/components/project-details/project-team/project-team.component.html
  frontend/src/app/components/projects/projects.component.html
  frontend/src/app/components/teams/new-team/new-team.component.html
  frontend/src/app/components/teams/teams.component.html
  frontend/src/app/components/translatorProfile/translator-profile/translator-profile.component.html
  frontend/src/app/components/workspace/key-details/tab-history/tab-history.component.html
  frontend/src/app/components/workspace/key-details/tab-optional/tab-optional.component.html
  frontend/src/app/dialogs/team-assign/team-assign.component.html
  frontend/src/app/services/user.service.ts
Labels: enhancement

#367 Feature/implement rights
  backend/Polyglot.BusinessLogic/Infrastructure.cs
  backend/Polyglot.BusinessLogic/Interfaces/IRightService.cs
  backend/Polyglot.BusinessLogic/Interfaces/ITeamService.cs
  backend/Polyglot.BusinessLogic/Services/RightService.cs
  backend/Polyglot.BusinessLogic/Services/TeamsService.cs
  backend/Polyglot.Core/Authentication/CurrentUser.cs
  backend/Polyglot.DataAccess/Migrations/20180830131209_AddUserRightView.Designer.cs
  backend/Polyglot.DataAccess/Migrations/20180830131209_AddUserRightView.cs
  backend/Polyglot.DataAccess/QueryTypes/QueryType.cs
  backend/Polyglot.DataAccess/QueryTypes/UserRights.cs
  backend/Polyglot.DataAccess/SqlRepository/DataContext.cs
  backend/Polyglot.DataAccess/SqlRepository/IUnitOfWork.cs
  backend/Polyglot.DataAccess/SqlRepository/UnitOfWork.cs
  backend/Polyglot.DataAccess/ViewsRepository/IViewData.cs
  backend/Polyglot.DataAccess/ViewsRepository/ViewData.cs
  backend/Polyglot/Controllers/ProjectsController.cs
  backend/Polyglot/Controllers/TeamsController.cs
  backend/Polyglot/Controllers/UserProfilesController.cs
  backend/Polyglot/appsettings.Development.json
  frontend/src/app/components/teams/team/team.component.ts
  frontend/src/app/models/translatorRights.ts
  frontend/src/app/services/right.service.spec.ts
  frontend/src/app/services/right.service.ts
  frontend/src/app/services/teams.service.ts
Labels: enhancement

#379 Feature/delete comment
  backend/Polyglot.BusinessLogic/Interfaces/IComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/ComplexStringService.cs
  backend/Polyglot.BusinessLogic/Services/SignalR/SignalRWorkspaceService.cs
  backend/Polyglot/Controllers/ComplexStringsController.cs
  backend/Polyglot/Startup.cs
  frontend/src/app/components/workspace/key-details/key-details.component.ts
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.html
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.sass
  frontend/src/app/components/workspace/key-details/tab-comments/tab-comments.component.ts
  frontend/src/app/models/comment.ts
  frontend/src/app/services/complex-string.service.ts
Labels: enhancement

#381 fix scroll when spinner appears
  frontend/src/app/components/projects/projects.component.html
  frontend/src/app/components/projects/projects.component.sass
  frontend/src/app/components/teams/teams.component.html
  frontend/src/app/components/teams/teams.component.sass
Labels: bug fix

#380 Added photo compression
  backend/Polyglot/Controllers/ComplexStringsController.cs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/new-project/new-project.component.ts
  frontend/src/app/components/upload-image/upload-image.component.html
  frontend/src/app/components/upload-image/upload-image.component.ts
  frontend/src/app/dialogs/cropper-dialog/cropper.component.html
  frontend/src/app/dialogs/cropper-dialog/cropper.component.ts
  frontend/src/app/dialogs/string-dialog/string-dialog.component.ts
  frontend/src/app/services/compress-file.service.ts
Labels: enhancement
